apiVersion: v2
name: kompass-insights
description: Kompass Insights for K8s
type: application
version: 2.2.3
appVersion: "v1.162.0"

dependencies:
- name: kompass-admission-controller
  alias: admission
  condition: admission.enabled
  repository: https://zesty-co.github.io/kompass-admission-controller
  version: 0.1.20
