{{- if and .Values.global.cxLogging .Values.global.cxLogging.enabled .Values.global.cxLogging.apiKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kompass.cxLogging.apiKeySecretName" (dict "cxLogging" .Values.global.cxLogging) | quote }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kompass.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ include "kompass.cxLogging.apiKeySecretKey" (dict "cxLogging" .Values.global.cxLogging) }}: {{ .Values.global.cxLogging.apiKey | quote }}
{{- end }}
