{{- if and .Values.global.imagePullSecret.name .Values.global.imagePullSecret.dockerconfigjson }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.global.imagePullSecret.name | quote }}
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-15"
    "helm.sh/hook-delete-policy": before-hook-creation
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ .Values.global.imagePullSecret.dockerconfigjson | quote }}
{{- end }}
