{{- include "kompass.validate.customReplicaAggregationMethods" . -}}
{{- include "kompass.validate.podPlacementRequiresRightsizing" . -}}
{{- include "kompass.validate.victoriaMetricsEnabled" . -}}
{{- include "kompass.validate.requiredLabels" . -}}
{{- include "kompass.validate.guardianRequestCeilings" . -}}
