{{- if .Values.cert-manager.enabled }}
  apiVersion: cert-manager.io/v1
  kind: ClusterIssuer
  metadata:
    name: kompass-selfsigned-issuer
    annotations:
    {{ if .Values.useHelmPriorityHooks }}
      helm.sh/hook: post-install,post-upgrade
      helm.sh/hook-weight: "15"
    {{ end }}
  spec:
    selfSigned: {}
{{- end }}
---
{{- if .Values.rightsizing.enabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kompass-pod-rightsizing-webhook-cert
  namespace: {{ .Release.Namespace }}  # Ensure it's deployed in the correct namespace
  annotations:
  {{ if .Values.useHelmPriorityHooks }}
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-weight: "20"
  {{ end }}
    cert-manager.io/disable-name-generation: "true"
  labels:
    {{- include "kompass.labels" . | nindent 4 }}
spec:
  secretName: {{ .Values.rightsizing.mutatingWebhookCertificateName }}
  dnsNames:
    - {{ include "kompass-webhook-svc.name" . }}.{{ .Release.Namespace }}.svc
    - {{" . }}.{{ .Release.Namespace }}.svc.cluster.local
  issuerRef:
    kind: ClusterIssuer
    name: {{ .Values.clusterIssuerName }}
{{- end }}
---
{{- if .Values.kompass-insights.admission.enabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kompass-admission-controller-cert
  namespace: {{ .Release.Namespace }}  # Ensure it's deployed in the correct namespace
  annotations:
  {{ if .Values.useHelmPriorityHooks }}
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-weight: "20"
  {{ end }}
    cert-manager.io/disable-name-generation: "true"
  labels:
    {{- include "kompass.labels" . | nindent 4 }}
spec:
  secretName: {{ .Values.kompass-insights.admission.mutatingWebhookCertificateName }}
  dnsNames:
    - {{ .Values.service.name }}.{{ .Release.Namespace }}.svc
    - {{ .Values.service.name }}.{{ .Release.Namespace }}.svc.cluster.local
  issuerRef:
    kind: ClusterIssuer
    name: kompass-selfsigned-issuer
{{- end }}
