{{- include "zesty-k8s.validate.credentialsSecret" . -}}
{{- if .Values.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name | quote }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "zesty-k8s.labels" . | nindent 4 }}
stringData:
  {{ .Values.secret.key | quote }}: {{ .Values.encryptedCredentials | quote }}
{{- end }}
