{{- if .Values.manager.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.manager.service }}"
  namespace: "{{ .Release.Namespace }}"
  labels:
    app.kubernetes.io/instance: "{{ include "zesty-k8s.fullname" . }}"
    app.kubernetes.io/name: "{{ include "zesty-k8s.fullname" . }}"
    {{- include "zesty-k8s.requiredLabels" . | nindent 4 }}
spec:
  selector:
    app.kubernetes.io/name: "{{ include "zesty-k8s.fullname" . }}"
  publishNotReadyAddresses: true
  ports:
    {{- with .Values.manager.ports.grpc }}
    - name: {{ .name }}
      port: {{ .containerPort }}
      targetPort: {{ .name }}
      protocol: {{ .protocol | default "TCP" }}
    {{- end }}
    {{- with .Values.manager.ports.metrics }}
    - name: {{ .name }}
      port: {{ .containerPort }}
      targetPort: {{ .name }}
      protocol: {{ .protocol | default "TCP" }}
    {{- end }}
    {{- with .Values.manager.ports.health }}
    - name: {{ .name }}
      port: {{ .containerPort }}
      targetPort: {{ .name }}
      protocol: {{ .protocol | default "TCP" }}
    {{- end }}
  type: ClusterIP
{{- end }}
