{{- $bridgeEnabled := index .Values.global "kompass-bridge" "enabled" | default false -}}
{{- $bridgeValues := index .Values "kompass-bridge" | default (dict) -}}
{{- $sa := $bridgeValues.serviceAccount | default (dict) -}}
{{- if and $bridgeEnabled $sa.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kompass.bridge.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kompass.bridge.labels" . | nindent 4 }}
  {{- with $sa.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
