{
 "title": "Multidimensional Autoscaling Dashboard",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_namespace_status_phase{phase=\"Active\"},namespace)"
    }
   },
   {
    "name": "workload_kind",
    "label": "Kind",
    "query": {
     "query": "label_values(kompass_container_cpu_usage_max_rate{namespace=\"$namespace\", created_by_kind!=\"virtualworkload\"},created_by_kind)"
    }
   },
   {
    "name": "workload_name",
    "label": "Workload",
    "query": {
     "query": "label_values(kompass_container_cpu_usage_max_rate{namespace=\"$namespace\", created_by_kind=\"$workload_kind\"},created_by_name)"
    }
   },
   {
    "name": "container",
    "label": "Container",
    "query": {
     "query": "label_values(kompass_container_cpu_usage_max_rate{namespace=\"$namespace\", created_by_name=\"$workload_name\", created_by_kind=\"$workload_kind\"},container)"
    }
   },
   {
    "name": "rs_policy",
    "label": "Rightsizing Policy",
    "query": "balanced, cost-focused, stability-focused"
   },
   {
    "name": "h_policy",
    "label": "Horizontal Policy",
    "query": "balanced, cost-focused, stability-focused"
   },
   { "name": "cpu_usage_percentile", "label": "CPU Usage Percentile", "query": "100" },
   { "name": "memory_usage_percentile", "label": "Memory Usage Percentile", "query": "100" }
  ]
 },
 "panels": [
  {
   "title": "Cpu Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(quantile by (container, resource_id, created_by_name, created_by_kind, namespace) ($cpu_usage_percentile/100, (rate(container_cpu_usage_seconds_total{container=~\"$container\",namespace=\"$namespace\"}[1m]) * on (namespace,pod,container) group_left (resource_id,created_by_name,created_by_kind) max by (namespace,pod,container,resource_id,created_by_name,created_by_kind) (kompass_pod_info{container=~\"$container\", namespace=\"$namespace\", created_by_name=\"$workload_name\",created_by_kind=\"$workload_kind\"})) or (0 * max by (namespace,pod,container,resource_id,created_by_name,created_by_kind) (kompass_pod_info{container=~\"$container\", namespace=\"$namespace\", created_by_name=\"$workload_name\",created_by_kind=\"$workload_kind\"}))))",
     "legendFormat": "Usage"
    },
    {
     "expr": "sum(avg(kompass_rs_recommendations{workload_name=\"$workload_name\", container=~\"$container\", namespace=\"$namespace\", resource_type=\"cpu\", mode=\"live\",resource_source=\"desired\", workload_kind=\"$workload_kind\"}[15s:15s])[1d])",
     "legendFormat": "Desired"
    },
    {
     "expr": "sum(avg((avg_over_time(avg(kube_pod_container_resource_requests{resource=\"cpu\", container=~\"$container\", namespace=\"$namespace\"}) by(pod, namespace, container, id))[5m]) * on(pod, namespace, container) group_left(owner_name) kompass_pod_info{namespace=\"$namespace\", workload_name=\"$workload_name\", container=~\"$container\", workload_kind=\"$workload_kind\"}) by (container))",
     "legendFormat": "Requests"
    },
    {
     "expr": "sum(avg(kompass_rs_recommendations{workload_name=\"$workload_name\", workload_kind=\"$workload_kind\", container=~\"$container\", namespace=\"$namespace\", resource_type=\"cpu\", mode=\"variants\",resource_source=\"desired\", rightsizing_policy=\"$rs_policy\", horizontal_policy=\"$h_policy\"}) by (rightsizing_policy)[1d]) by (rightsizing_policy)",
     "legendFormat": "{{horizontal_policy}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(quantile by (container, resource_id, created_by_name, created_by_kind, namespace) ($memory_usage_percentile/100, (container_memory_working_set_bytes{container=~\"$container\",namespace=\"$namespace\"} * on (namespace,pod,container) group_left (resource_id,created_by_name,created_by_kind) max by (namespace,pod,container,resource_id,created_by_name,created_by_kind) (kompass_pod_info{container=~\"$container\", namespace=\"$namespace\", created_by_name=\"$workload_name\",created_by_kind=\"$workload_kind\"})) or (0 * max by (namespace,pod,container,resource_id,created_by_name,created_by_kind) (kompass_pod_info{container=~\"$container\", namespace=\"$namespace\", created_by_name=\"$workload_name\",created_by_kind=\"$workload_kind\"}))) / 1024 / 1024)",
     "legendFormat": "Usage"
    },
    {
     "expr": "sum(avg(kompass_rs_recommendations{namespace=\"$namespace\", container=~\"$container\", resource_type=\"memory\", mode=\"live\", resource_source=\"desired\", workload_name=\"$workload_name\", workload_kind=\"$workload_kind\"}[15s:15s])[1d] / 1024 / 1024)",
     "legendFormat": "Desired"
    },
    {
     "expr": "sum(avg((avg_over_time(avg(kube_pod_container_resource_requests{resource=\"memory\", container=~\"$container\", namespace=\"$namespace\"}) by(pod, namespace, container, id))[5m]) * on(pod, namespace, container) group_left(owner_name) kompass_pod_info{namespace=\"$namespace\", workload_name=\"$workload_name\", workload_kind=\"$workload_kind\", container=~\"$container\"}) by (container)  / 1024 / 1024)",
     "legendFormat": "Requests"
    },
    {
     "expr": "sum(avg(kompass_rs_recommendations{workload_name=\"$workload_name\", workload_kind=\"$workload_kind\", container=~\"$container\", namespace=\"$namespace\", resource_type=\"memory\", mode=\"variants\",resource_source=\"desired\", rightsizing_policy=\"$rs_policy\", horizontal_policy=\"$h_policy\"}) by (rightsizing_policy) [1d] / 1024 / 1024) by (rightsizing_policy)",
     "legendFormat": "{{rightsizing_policy}}"
    }
   ]
  },
  {
   "title": "Replicas Count",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "count(kube_pod_container_info{container=\"$container\", namespace=\"$namespace\"} * on (namespace, pod, container) group_left(workload_name) kompass_pod_info{workload_name=\"$workload_name\"})",
     "legendFormat": "Current Replica Count"
    },
    {
     "expr": "kube_horizontalpodautoscaler_spec_min_replicas{namespace=\"$namespace\"}\n  * on (namespace, horizontalpodautoscaler)\n    group_left(scaletargetref_kind, scaletargetref_name)\n    kube_horizontalpodautoscaler_info{\n      namespace=\"$namespace\",\n      scaletargetref_kind=\"Deployment\",\n      scaletargetref_name=\"$workload_name\"\n    }",
     "legendFormat": "Min Replica Count"
    },
    {
     "expr": "kompass_rs_recommendations{\n  resource_type=\"hpa_min_replica\",\n  workload_name=\"$workload_name\",\n  namespace=\"$namespace\",\n  resource_source=\"desired\",\n  mode=\"live\",\n}",
     "legendFormat": "Desired Min Replica Count"
    },
    {
     "expr": "kompass_rs_recommendations{workload_name=\"$workload_name\", namespace=\"$namespace\", resource_type=\"hpa_min_replica\", mode=\"variants\",resource_source=\"desired\", rightsizing_policy=\"$rs_policy\", horizontal_policy=\"$h_policy\"}[1d]",
     "legendFormat": "{{horizontal_policy}}"
    }
   ]
  },
  {
   "title": "Events (Throttling/OOM)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 6 },
   "targets": [
    {
     "expr": "sum(increase(container_cpu_cfs_throttled_seconds_total{container=~\"$container\", namespace=\"$namespace\"}[5m]) * on (container, pod, namespace) group_left (created_by_name, created_by_kind) max(max_over_time(kompass_pod_info{workload_name=\"$workload_name\", workload_kind=\"$workload_kind\", container=~\"$container\", namespace=\"$namespace\"}[5m])) by (container, pod, created_by_name, created_by_kind, namespace)) by (namespace, created_by_name, created_by_kind)",
     "legendFormat": "Throttling"
    },
    {
     "expr": "sum((delta(kube_pod_container_status_restarts_total{container=~\"$container\", namespace=\"$namespace\"}[1m])  > 0) * on (pod, container, namespace) (kube_pod_container_status_last_terminated_reason{reason=\"OOMKilled\", container=~\"$container\", namespace=\"$namespace\"}  > 0) * on (container, pod, namespace) group_left (created_by_name, created_by_kind) max(kompass_pod_info{workload_name=\"$workload_name\", workload_kind=\"$workload_kind\", container=~\"$container\", namespace=\"$namespace\"}) by (container, pod, namespace, created_by_name, created_by_kind)) by (created_by_name, created_by_kind, namespace)",
     "legendFormat": "OOM"
    }
   ]
  },
  {
   "title": "HPA",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "expr": "kube_horizontalpodautoscaler_spec_target_metric{metric_name=\"cpu\", namespace=\"$namespace\"} * on (horizontalpodautoscaler) group_left () kube_horizontalpodautoscaler_info{scaletargetref_name=\"$workload_name\", namespace=\"$namespace\"}",
     "legendFormat": "HPA CPU Target"
    },
    {
     "expr": "kube_horizontalpodautoscaler_spec_target_metric{metric_name=\"memory\", namespace=\"$namespace\"} * on (horizontalpodautoscaler) group_left () kube_horizontalpodautoscaler_info{scaletargetref_name=\"$workload_name\", namespace=\"$namespace\"}",
     "legendFormat": "HPA Memory Target"
    },
    {
     "expr": "kompass_rs_recommendations{workload_name=\"$workload_name\", workload_kind=\"$workload_kind\", resource_type=\"hpa_cpu\", mode=\"live\", workload_name=\"$workload_name\", resource_source=\"desired\", namespace=\"$namespace\"}",
     "legendFormat": "Desired Hpa CPU"
    },
    {
     "expr": "kompass_rs_recommendations{workload_name=\"$workload_name\", workload_kind=\"$workload_kind\", resource_type=\"hpa_memory\", mode=\"live\", workload_name=\"$workload_name\", resource_source=\"desired\", namespace=\"$namespace\"}",
     "legendFormat": "Desired Hpa Memory"
    },
    {
     "expr": "kompass_rs_recommendations{workload_name=\"$workload_name\", workload_kind=\"$workload_kind\", resource_type=\"hpa_cpu\", mode=\"variants\", workload_name=\"$workload_name\", resource_source=\"desired\", namespace=\"$namespace\", rightsizing_policy=\"$rs_policy\", horizontal_policy=\"$h_policy\"}",
     "legendFormat": "{{rightsizing_policy}} - CPU"
    },
    {
     "expr": "kompass_rs_recommendations{workload_name=\"$workload_name\", workload_kind=\"$workload_kind\", resource_type=\"hpa_memory\", mode=\"variants\", workload_name=\"$workload_name\", resource_source=\"desired\", namespace=\"$namespace\", rightsizing_policy=\"$rs_policy\", horizontal_policy=\"$h_policy\"}",
     "legendFormat": "{{rightsizing_policy}} - Memory"
    }
   ]
  },
  {
   "title": "Audit table",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "kompass_rs_recommendations{workload_name=\"$workload_name\", workload_kind=\"$workload_kind\", mode=\"live\", namespace=\"$namespace\"}[$__range]",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 23 },
   "targets": [
    { "expr": "kompass_rs_errors", "legendFormat": "__auto" }
   ]
  }
 ]
}