{
 "title": "Pod-RightSizing Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "query_result(kube_namespace_status_phase{phase=\"Active\"})"
    }
   },
   {
    "name": "workload_name",
    "label": "Workload Name",
    "query": {
     "query": "query_result(sort(label_replace(kube_deployment_metadata_generation{namespace=\"$namespace\"}, \"name\", \"$1\", \"deployment\", \"(.+)\") or label_replace(kube_statefulset_metadata_generation{namespace=\"$namespace\"}, \"name\", \"$1\", \"statefulset\", \"(.+)\") or label_replace(kube_daemonset_metadata_generation{namespace=\"$namespace\"}, \"name\", \"$1\", \"daemonset\", \"(.+)\")))"
    }
   },
   {
    "name": "container",
    "query": {
     "query": "query_result(kube_pod_container_info{namespace=\"$namespace\"} * on(pod) group_left(created_by_name) kompass_pod_info{created_by_name=\"$workload_name\", namespace=\"$namespace\"})"
    }
   },
   {
    "name": "policy",
    "query": "default, conservative, cost-focused, stability-focused, all, none"
   },
   {
    "name": "BufferPercent",
    "query": "0, 10, 20, 30, 40, 50, 60, 70, 80, 90"
   },
   { "name": "LookbackPeriod", "query": "1d" }
  ]
 },
 "panels": [
  {
   "title": "Cpu Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "kompass_container_cpu_usage_max_rate{container=\"$container\", namespace=\"$namespace\", created_by_name=\"$workload_name\"}",
     "legendFormat": "Usage: {{container}}"
    },
    {
     "expr": "avg(kompass_rs_recommendations{workload_name=\"$workload_name\", container=\"$container\", namespace=\"$namespace\", resource_type=\"cpu\", mode=\"live\",resource_source=\"desired\"}[15s:15s])[1d]",
     "legendFormat": "Desired: {{container}}"
    },
    {
     "expr": "(avg_over_time(avg(kube_pod_container_resource_requests{resource=\"cpu\", container=\"$container\", namespace=\"$namespace\"}) by(pod, namespace, container, id))[5m]) * on(pod, namespace) group_left(owner_name) kompass_pod_info{namespace=\"$namespace\", workload_name=\"$workload_name\"}",
     "legendFormat": "Requests: {{container}}"
    },
    {
     "expr": "avg(kompass_rs_recommendations{workload_name=\"$workload_name\", container=\"$container\", namespace=\"$namespace\", resource_type=\"cpu\", mode=\"variants\",resource_source=\"desired\", source_apc=\"conservative-policy\"})[1d] * (\"$policy\" == 'conservative' or \"$policy\" == 'all')",
     "legendFormat": "Conservative Policy: {{container}}"
    },
    {
     "expr": "avg(kompass_rs_recommendations{workload_name=\"$workload_name\", container=\"$container\", namespace=\"$namespace\", resource_type=\"cpu\", mode=\"variants\",resource_source=\"desired\", source_apc=\"default-policy\"})[1d] * (\"$policy\" == 'default' or \"$policy\" == 'all')",
     "legendFormat": "Default Policy: {{container}}"
    },
    {
     "expr": "avg(kompass_rs_recommendations{workload_name=\"$workload_name\", container=\"$container\", namespace=\"$namespace\", resource_type=\"cpu\", mode=\"variants\",resource_source=\"desired\", source_apc=\"cost-focused-policy\"})[1d] * (\"$policy\" == 'cost-focused' or \"$policy\" == 'all')",
     "legendFormat": "Default Policy: {{container}}"
    },
    {
     "expr": "avg(kompass_rs_recommendations{workload_name=\"$workload_name\", container=\"$container\", namespace=\"$namespace\", resource_type=\"cpu\", mode=\"variants\",resource_source=\"desired\", source_apc=\"stability-focused-policy\"})[1d] * (\"$policy\" == 'stability-focused' or \"$policy\" == 'all')",
     "legendFormat": "Default Policy: {{container}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "kompass_container_memory_usage_max{container=\"$container\", namespace=\"$namespace\", created_by_name=\"$workload_name\" } / 1024 / 1024",
     "legendFormat": "Usage: {{container}}"
    },
    {
     "expr": "avg(kompass_rs_recommendations{namespace=\"$namespace\", container=\"$container\", resource_type=\"memory\", mode=\"live\", resource_source=\"desired\", workload_name=\"$workload_name\"}[15s:15s])[1d] / 1024 / 1024",
     "legendFormat": "Desired: {{container}}"
    },
    {
     "expr": "(avg_over_time(avg(kube_pod_container_resource_requests{resource=\"memory\", container=\"$container\", namespace=\"$namespace\"}) by(pod, namespace, container, id))[5m]) * on(pod, namespace) group_left(owner_name) kompass_pod_info{namespace=\"$namespace\", workload_name=\"$workload_name\"}  / 1024 / 1024",
     "legendFormat": "Requests: {{container}}"
    },
    {
     "expr": "avg(kompass_rs_recommendations{workload_name=\"$workload_name\", container=\"$container\", namespace=\"$namespace\", resource_type=\"memory\", mode=\"variants\",resource_source=\"desired\", source_apc=\"conservative-policy\"})[1d] / 1024 / 1024 * (\"$policy\" == 'conservative' or \"$policy\" == 'all')",
     "legendFormat": "Conservative Policy: {{container}}"
    },
    {
     "expr": "avg(kompass_rs_recommendations{workload_name=\"$workload_name\", container=\"$container\", namespace=\"$namespace\", resource_type=\"memory\", mode=\"variants\",resource_source=\"desired\", source_apc=\"default-policy\"})[1d] / 1024 / 1024 * (\"$policy\" == 'default' or \"$policy\" == 'all')",
     "legendFormat": "Default Policy: {{container}}"
    },
    {
     "expr": "avg(kompass_rs_recommendations{workload_name=\"$workload_name\", container=\"$container\", namespace=\"$namespace\", resource_type=\"memory\", mode=\"variants\",resource_source=\"desired\", source_apc=\"cost-focused-policy\"})[1d] / 1024 / 1024 * (\"$policy\" == 'cost-focused' or \"$policy\" == 'all')",
     "legendFormat": "Default Policy: {{container}}"
    },
    {
     "expr": "avg(kompass_rs_recommendations{workload_name=\"$workload_name\", container=\"$container\", namespace=\"$namespace\", resource_type=\"memory\", mode=\"variants\",resource_source=\"desired\", source_apc=\"stability-focused-policy\"})[1d] / 1024 / 1024 * (\"$policy\" == 'stability-focused' or \"$policy\" == 'all')",
     "legendFormat": "Default Policy: {{container}}"
    }
   ]
  },
  {
   "title": "Replicas Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "count(kube_pod_container_info{container=\"$container\", namespace=\"$namespace\"} * on (namespace, pod, container) group_left(workload_name) kompass_pod_info{workload_name=\"$workload_name\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Events (Throttling/OOM)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 8 },
   "targets": [
    {
     "expr": "sum(increase(container_cpu_cfs_throttled_seconds_total{container=\"$container\", namespace=\"$namespace\"}[5m]) * on (container, pod, namespace) group_left (created_by_name, created_by_kind) max(max_over_time(kompass_pod_info{workload_name=\"$workload_name\", container=\"$container\", namespace=\"$namespace\"}[5m])) by (container, pod, created_by_name, created_by_kind, namespace)) by (container, namespace, created_by_name, created_by_kind)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum((delta(kube_pod_container_status_restarts_total{container=\"$container\", namespace=\"$namespace\"}[1m])  > 0) * on (pod, container, namespace) (kube_pod_container_status_last_terminated_reason{reason=\"OOMKilled\", container=\"$container\", namespace=\"$namespace\"}  > 0) * on (container, pod, namespace) group_left (created_by_name, created_by_kind) max(kompass_pod_info{workload_name=\"$workload_name\", container=\"$container\", namespace=\"$namespace\"}) by (container, pod, namespace, created_by_name, created_by_kind)) by (container, created_by_name, created_by_kind, namespace)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HPA",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "kube_horizontalpodautoscaler_spec_target_metric{metric_name=\"cpu\", namespace=\"$namespace\"} * on (horizontalpodautoscaler) group_left () kube_horizontalpodautoscaler_info{scaletargetref_name=\"$workload_name\", namespace=\"$namespace\"}",
     "legendFormat": "HPA CPU"
    },
    {
     "expr": "kube_horizontalpodautoscaler_spec_target_metric{metric_name=\"memory\", namespace=\"$namespace\"} * on (horizontalpodautoscaler) group_left () kube_horizontalpodautoscaler_info{scaletargetref_name=\"$workload_name\", namespace=\"$namespace\"}",
     "legendFormat": "HPA Memory"
    },
    {
     "expr": "kompass_rs_recommendations{workload_name=\"$workload_name\", resource_type=\"hpa_cpu\", mode=\"live\", workload_name=\"$workload_name\", resource_source=\"desired\", namespace=\"$namespace\"}",
     "legendFormat": "Desired Hpa CPU"
    },
    {
     "expr": "kompass_rs_recommendations{workload_name=\"$workload_name\", resource_type=\"hpa_memory\", mode=\"live\", workload_name=\"$workload_name\", resource_source=\"desired\", namespace=\"$namespace\"}",
     "legendFormat": "Desired Hpa Memory"
    }
   ]
  },
  {
   "title": "Audit table",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "kompass_rs_recommendations{workload_name=\"$workload_name\", mode=\"live\", namespace=\"$namespace\", container=\"$container\"}[$__range]",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 27 },
   "targets": [
    { "expr": "kompass_rs_errors", "legendFormat": "__auto" }
   ]
  }
 ]
}