apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kompass-pod-placement.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kompass-pod-placement.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "kompass-pod-placement.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "kompass-pod-placement.labels" . | nindent 8 }}
      {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      serviceAccountName: {{ include "kompass-pod-placement.fullname" . }}
      {{- $pullSecrets := include "kompass-pod-placement.imagePullSecrets" . | fromYamlArray }}
      {{- if $pullSecrets }}
      imagePullSecrets:
        {{- toYaml $pullSecrets | nindent 8 }}
      {{- end }}
      {{- $defaultPodSC := include "kompass-pod-placement.defaultPodSecurityContext" . | fromYaml -}}
      {{- $podSecurityContext := mergeOverwrite
        (mergeOverwrite
          (deepCopy ($defaultPodSC | default dict))
          (.Values.podSecurityContext | default dict)
        )
        (.Values.global.podSecurityContext | default dict)
      -}}
      {{- $securityContext := mergeOverwrite
        (deepCopy (.Values.securityContext | default dict))
        (.Values.global.securityContext | default dict)
      -}}
      {{- with $podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      affinity:
        {{- include "kompass-pod-placement.affinity" . | nindent 8 }}
      containers:
        - name: pod-placement
          {{- with $securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ include "kompass-pod-placement.image" . }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - "--probe-addr=:{{ .Values.ports.health.containerPort }}"
            - "--metrics-addr=:{{ .Values.ports.metrics.containerPort }}"
            {{- if .Values.evictionWindow.schedule }}
            - "--eviction-window-schedule={{ .Values.evictionWindow.schedule }}"
            - "--eviction-window-duration={{ .Values.evictionWindow.duration }}"
            {{- end }}
            {{- range .Values.extraArgs }}
            - {{ . | quote }}
            {{- end }}
          env:
            - name: ZESTY_SECRET_NAME
              value: {{ .Values.kompassInsightSecret }}
            - name: KOMPASS_CHART_VERSION
              value: {{ .Chart.Version }}
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: READ_ONLY_MODE
              value: {{ not .Values.enabled | toString | quote }}
            {{- if and .Values.global.cxLogging .Values.global.cxLogging.enabled }}
            - name: CX_CLUSTER_NAME
              value: {{ .Values.global.cxLogging.clusterName }}
            - name: CX_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ dig "apiKeySecret" "name" "kompass-cx-logging" .Values.global.cxLogging | quote }}
                  key: {{ dig "apiKeySecret" "key" "CX_API_KEY" .Values.global.cxLogging | quote }}
                  optional: true
            - name: CORALOGIX_INGRESS_URL
              {{- /*
                For backward compatibility, if the cxLogging.otelEndpoint is provided, use it to generate the ingressUrl.
                To remove in the future.
              */}}
              {{- if .Values.global.cxLogging.otelEndpoint }}
              value: https://{{ .Values.global.cxLogging.otelEndpoint }}/
              {{- else }}
              value: {{ .Values.global.cxLogging.ingressUrl }}
              {{- end }}
            {{- else if and .Values.cxLogging .Values.cxLogging.enabled }}
            - name: CX_CLUSTER_NAME
              value: {{ .Values.cxLogging.clusterName }}
            - name: CX_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ dig "apiKeySecret" "name" "kompass-cx-logging" .Values.cxLogging | quote }}
                  key: {{ dig "apiKeySecret" "key" "CX_API_KEY" .Values.cxLogging | quote }}
                  optional: true
            - name: CORALOGIX_INGRESS_URL
              {{- /*
                For backward compatibility, if the cxLogging.otelEndpoint is provided, use it to generate the ingressUrl.
                To remove in the future.
              */}}
              {{- if .Values.cxLogging.otelEndpoint }}
              value: https://{{ .Values.cxLogging.otelEndpoint }}/
              {{- else }}
              value: {{ .Values.cxLogging.ingressUrl }}
              {{- end }}
            {{- end }}
            {{- with .Values.env }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- with .Values.envFrom }}
          envFrom:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
            - name: {{ .Values.ports.https.name }}
              containerPort: {{ .Values.ports.https.containerPort }}
              protocol: {{ .Values.ports.https.protocol }}
            - name: {{ .Values.ports.metrics.name }}
              containerPort: {{ .Values.ports.metrics.containerPort }}
              protocol: {{ .Values.ports.metrics.protocol }}
            - name: {{ .Values.ports.health.name }}
              containerPort: {{ .Values.ports.health.containerPort }}
              protocol: {{ .Values.ports.health.protocol }}
          readinessProbe:
            {{- toYaml .Values.probes.readiness | nindent 12 }}
          livenessProbe:
            {{- toYaml .Values.probes.liveness | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
          {{- if and .Values.enabled .Values.webhook.enabled }}
            - mountPath: "/tmp/k8s-webhook-server/serving-certs"
              name: webhook-tls
              readOnly: true
          {{- end }}
          {{- with .Values.extraVolumeMounts }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        {{- if and .Values.enabled .Values.webhook.enabled }}
        - name: webhook-tls
          secret:
            secretName: {{ include "kompass-pod-placement.webhook.certificateName" . }}
        {{- end }}
      {{- with .Values.extraVolumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
