name: trigger-jenkins

on:
  pull_request:

jobs:
  jenkins:
    name: Trigger Jenkins
    runs-on: gh-runner-staging
    container:
      image: ubuntu:25.04

    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: trigger installation pipeline
        uses: toptal/jenkins-job-trigger-action@master
        with:
          jenkins_url: ${{ secrets.JENKINS_URL }}
          jenkins_user: ${{ secrets.JENKINS_USER }}
          jenkins_token: ${{ secrets.JENKINS_API_TOKEN }}
          proxy: ${{ secrets.JENKINS_PROXY }}
          job_name: "Run_Unified_Installation_pipline"
          job_params: |
            {
              "UNIFIED_INSTALLATION_BRANCH": "${{ github.head_ref }}"
            }
          job_timeout: "1200"
