name: trigger-jenkins

on:
  pull_request:

jobs:
  jenkins:
    permissions:
      contents: read
    name: Trigger Jenkins
    runs-on: gh-runner-staging
    container:
      image: ubuntu:25.04

    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: trigger installation pipeline
        uses: joshlk/jenkins-githubaction@master
        with:
          url: ${{ secrets.JENKINS_URL }}
          job_name: "Run_Unified_Installation_pipline"
          user: ${{ secrets.JENKINS_USER }}
          token: ${{ secrets.JENKINS_TOKEN }}
          parameters: {"UNIFIED_INSTALLATION_BRANCH": "${{ github.head_ref }}"}
          interval: 30
          timeout: "20000"
