name: trigger-jenkins

on:
  pull_request:

jobs:
  jenkins:
    name: Trigger Jenkins
    runs-on: gh-runner-staging

    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: trigger single Job
        uses: appleboy/jenkins-action@master
        with:
          url: ${{ secrets.JENKINS_URL }}
          user: ${{ secrets.JENKINS_USER }}
          token: ${{ secrets.JENKINS_API_TOKEN }}
          job: "Run_Test_Flow"
          parameters: UNIFIED_INSTALLATION_BRANCH=${{ github.head_ref }}
