name: Deploy Chart To ECR

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    if: "!startsWith(github.event.head_commit.message, 'chore:')"
    runs-on: [gh-runner-production]
    container:
      image: alpine:3.22.1
      env:
        AWS_WEB_IDENTITY_TOKEN_FILE: /var/run/secrets/eks.amazonaws.com/serviceaccount/token
        AWS_ROLE_ARN: ${{ secrets.AWS_ROLE_ARN }}
      volumes:
        - /var/run/secrets/eks.amazonaws.com/serviceaccount/token:/var/run/secrets/eks.amazonaws.com/serviceaccount/token
    permissions:
      contents: read

    steps:
      - name: Install Utilites
        run: |
          apk add --no-cache bash tar curl git aws-cli helm
          
      - name: Package Chart
        run: |
          cd charts/kompass
          helm dep update
          helm dep build . 
          helm package .

      - name: Deploy Chart To ECR
        run: |
          for region in $(echo $AVAILABLE_ECR_REGIONS | tr "," "\n")
          do
            aws ecr get-login-password --region $region | helm registry login --username AWS --password-stdin  ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.$region.amazonaws.com

            helm push charts/kompass/kompass-*.tgz --registry oci://${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.$region.amazonaws.com/
          done
